/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AcademiaProgramador_CarlosArthurSantili;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos
 */
public class JanelaEquipamento extends javax.swing.JFrame {

    /**
     * Creates new form JanelaEquipamento
     */
    int auxAdicionar = 0;
    int qtdElementosTabela = 0;
    ArrayList<Equipamento> listaEquipamento = new ArrayList<Equipamento>();
    
    public JanelaEquipamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frameEquipamento = new javax.swing.JPanel();
        textNome = new javax.swing.JTextField();
        textPreco = new javax.swing.JTextField();
        textNumeroSerie = new javax.swing.JTextField();
        textDataFabricacao = new javax.swing.JTextField();
        bt_Adicionar = new javax.swing.JButton();
        bt_Atualizar = new javax.swing.JButton();
        bt_Deletar = new javax.swing.JButton();
        bt_Fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textFabricante = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEquipamento = new javax.swing.JTable();
        bt_Manutencao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        bt_Adicionar.setText("Adicionar");
        bt_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AdicionarActionPerformed(evt);
            }
        });

        bt_Atualizar.setText("Atualizar");
        bt_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AtualizarActionPerformed(evt);
            }
        });

        bt_Deletar.setText("Deletar");
        bt_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DeletarActionPerformed(evt);
            }
        });

        bt_Fechar.setText("Fechar");
        bt_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_FecharActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Gerenciador de Equipamentos");

        jLabel2.setText("Nome");

        jLabel3.setText("Preço Aquisição");

        jLabel4.setText("Número de Série");

        jLabel5.setText("Data Fabricação");

        jLabel6.setText("Fabricante");

        tabelaEquipamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço Aquisição", "Número de Série", "Data Fabricação", "Fabricante"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaEquipamento);

        bt_Manutencao.setText("Manutenção");
        bt_Manutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ManutencaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameEquipamentoLayout = new javax.swing.GroupLayout(frameEquipamento);
        frameEquipamento.setLayout(frameEquipamentoLayout);
        frameEquipamentoLayout.setHorizontalGroup(
            frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameEquipamentoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEquipamentoLayout.createSequentialGroup()
                                .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textNumeroSerie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                    .addComponent(textPreco, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(textNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEquipamentoLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEquipamentoLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(textDataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEquipamentoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_Adicionar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Atualizar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Deletar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Manutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frameEquipamentoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(274, 274, 274))
        );
        frameEquipamentoLayout.setVerticalGroup(
            frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameEquipamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frameEquipamentoLayout.createSequentialGroup()
                        .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textNumeroSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textDataFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_Fechar)
                    .addGroup(frameEquipamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt_Adicionar)
                        .addComponent(bt_Atualizar)
                        .addComponent(bt_Deletar)
                        .addComponent(bt_Manutencao)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(frameEquipamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AdicionarActionPerformed
        // TODO add your handling code here:
        
        if (textNome.getText().length() < 6)
                {
                    JOptionPane optionPane = new JOptionPane("Não é possível adicionar nome com menos que 6 letras", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: Nome_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else if (textPreco.getText().length() < 1)
                {
                    JOptionPane optionPane = new JOptionPane("É necessário adicionar um valor para o campo preço de aquisição", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: Preco_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else if (textNumeroSerie.getText().length() < 1)
                {
                    JOptionPane optionPane = new JOptionPane("É necessário adicionar um valor para o campo número de série", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: NumeroSerie_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else if (textDataFabricacao.getText().length() < 1)
                {
                    JOptionPane optionPane = new JOptionPane("É necessário adicionar um valor para o campo data de fabricação", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: DataFabricacao_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else if (textFabricante.getText().length() < 1)
                {
                    JOptionPane optionPane = new JOptionPane("É necessário adicionar um valor para o campo fabricante", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: Fabricante_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else
                {
                    Equipamento e = new Equipamento();
                    e.setNome(textNome.getText());
                    e.setPreco(Double.parseDouble(textPreco.getText()));
                    e.setNumeroSerie(Integer.parseInt(textNumeroSerie.getText()));
                    e.setNome(textNome.getText());
                    e.setNome(textNome.getText());
                    
                    listaEquipamento.add(e);
                    
                    
                    Object[] row = new Object[5];
                    
                    row[0] = textNome.getText();
                    row[1] = textPreco.getText();
                    row[2] = textNumeroSerie.getText();
                    row[3] = textDataFabricacao.getText();
                    row[4] = textFabricante.getText();
                    
                    DefaultTableModel model = (DefaultTableModel) tabelaEquipamento.getModel();

                    model.addRow(row);
                    qtdElementosTabela++;
                    
                    
                    /*
                    Adicionar ao txt
                    for (Equipamento j : listaEquipamento)
                    {
                        j.gravarTxt();
                    }
                    */
                    
                    
                }
    }//GEN-LAST:event_bt_AdicionarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void bt_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AtualizarActionPerformed
        // TODO add your handling code here:
            int i = tabelaEquipamento.getSelectedRow();
                
                if(tabelaEquipamento.getSelectedRow()<0)
                {
                    JOptionPane optionPane = new JOptionPane("É necessário selecionar o item que você deseja alterar", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: AlterarEquipamento_SelectedRow<0");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else if (textNome.getText().length() < 6)
                {
                    JOptionPane optionPane = new JOptionPane("Não é possível adicionar nome com menos que 6 letras", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: Nome_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else if (textPreco.getText().length() < 1)
                {
                    JOptionPane optionPane = new JOptionPane("É necessário adicionar um valor para o campo preço de aquisição", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: Preco_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else if (textNumeroSerie.getText().length() < 1)
                {
                    JOptionPane optionPane = new JOptionPane("É necessário adicionar um valor para o campo número de série", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: NumeroSerie_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else if (textDataFabricacao.getText().length() < 1)
                {
                    JOptionPane optionPane = new JOptionPane("É necessário adicionar um valor para o campo data de fabricação", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: DataFabricacao_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else if (textFabricante.getText().length() < 1)
                {
                    JOptionPane optionPane = new JOptionPane("É necessário adicionar um valor para o campo fabricante", JOptionPane.ERROR_MESSAGE);    
                    JDialog dialog = optionPane.createDialog("ERRO: Fabricante_QtdCaracteres");
                    dialog.setAlwaysOnTop(true);
                    dialog.setVisible(true);
                }
                else
                {
                    
                        listaEquipamento.get(i).setNome(textNome.getText());
                        listaEquipamento.get(i).setPreco(Double.parseDouble(textPreco.getText()));
                        listaEquipamento.get(i).setNumeroSerie(Integer.parseInt(textNumeroSerie.getText()));
                        listaEquipamento.get(i).setNome(textNome.getText());
                        listaEquipamento.get(i).setNome(textNome.getText());


                        Object[] row = new Object[5];

                        row[0] = textNome.getText();
                        row[1] = textPreco.getText();
                        row[2] = textNumeroSerie.getText();
                        row[3] = textDataFabricacao.getText();
                        row[4] = textFabricante.getText();
                        DefaultTableModel model = (DefaultTableModel) tabelaEquipamento.getModel();

                        model.setValueAt(textNome.getText(), i, 0);
                        model.setValueAt(textPreco.getText(), i, 1);
                        model.setValueAt(textNumeroSerie.getText(), i, 2);
                        model.setValueAt(textDataFabricacao.getText(), i, 3);
                        model.setValueAt(textFabricante.getText(), i, 4);
                }
    }//GEN-LAST:event_bt_AtualizarActionPerformed

    private void bt_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DeletarActionPerformed
        // TODO add your handling code here:
        int i = tabelaEquipamento.getSelectedRow();
            if(i >= 0)
            {
                listaEquipamento.remove(i);
                DefaultTableModel model = (DefaultTableModel) tabelaEquipamento.getModel();
                model.removeRow(i);
                qtdElementosTabela--;
            }
            else
            {
                JOptionPane optionPane = new JOptionPane("Erro ao deletar, selecione um item valido", JOptionPane.ERROR_MESSAGE);    
                JDialog dialog = optionPane.createDialog("ERRO: DeleteEquipamento_SelectedRow<0");
                dialog.setAlwaysOnTop(true);
                dialog.setVisible(true);
            } 
    }//GEN-LAST:event_bt_DeletarActionPerformed

    private void bt_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_FecharActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_bt_FecharActionPerformed

    private void bt_ManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ManutencaoActionPerformed
        // TODO add your handling code here:
        JanelaManutencao jM = new JanelaManutencao(listaEquipamento);
        jM.setVisible(true);
    }//GEN-LAST:event_bt_ManutencaoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Adicionar;
    private javax.swing.JButton bt_Atualizar;
    private javax.swing.JButton bt_Deletar;
    private javax.swing.JButton bt_Fechar;
    private javax.swing.JButton bt_Manutencao;
    private javax.swing.JPanel frameEquipamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEquipamento;
    private javax.swing.JTextField textDataFabricacao;
    private javax.swing.JTextField textFabricante;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNumeroSerie;
    private javax.swing.JTextField textPreco;
    // End of variables declaration//GEN-END:variables
}
